---
title: "FishSurvey_Final"
author: "Bart_DiFiore"
date: "April 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = F, include = F)
```

```{r getdata}

#########
#Get Data
#########

setwd("/Users/bartdifiore/Dropbox/Thesis_Research/DataforAnalysis/")
library(reshape)
library(MASS)
library(car)
library(plyr)
library(dplyr)
library(lme4)
library(ggplot2)


Names <- read.csv("RawFiles/Unique_Species_revised.csv", header = TRUE) # Read in the file with the metadata. 

VS <- read.table("RawFiles/VisualSurveys_WorkingFile.txt", header = TRUE, sep = "\t") # Readin the master file. 
t <- unique(VS$Species.Ident) #save the unique species names
vs <- VS[VS$Species.Ident != t[33], ] # get rid of the problematic "C.Rostrada"... we didn't see any anyway... 

VS.Master <- merge(vs, Names) # merge the two files

RecordNum.S <- order(VS.Master$Record.Num) # create a sort object on the record number (record number to so as to maintain the original sort)

VS.Master <- VS.Master[RecordNum.S, ] # Sort the master file by the sort object.  

VS.Master[, c(14:27)][is.na(VS.Master[, c(14:27)])] <- 0

patch <- read.table("RawFiles/PatchCharacteristics.csv", header = TRUE, sep = ",")
rug <- patch[,c(1,10, 23)]
rug$pnum.f <- as.factor(rug$pnum)

NT <- read.csv("RawFiles/NT_merge.csv")
names(NT) <- c("UniquePatch.Num", "NoTake", "sub")

VS.Master <- merge(VS.Master, NT)

#Fix the parrotfish issue...

VS.Master$ident.cor <- ifelse(VS.Master$sub == "Seagrass" & VS.Master$Common.Ident == "Parrotfish_Unident" & VS.Master$T2.0_5 > 0, "JuvenilleParrot_Unident", paste(VS.Master$Common.Ident))

VS.Master$Common.Ident <- as.factor(VS.Master$ident.cor)
VS.Master <- VS.Master[,-39]

# Fix the pisc.herb.invert issue 

VS.Master$Piscivore_Herbivore <- addNA(VS.Master$Piscivore_Herbivore)
levels(VS.Master$Piscivore_Herbivore) <- c("Herb", "Invert", "Pisc", "other")

#Other files needed later
numtransects <- read.csv("RawFiles/numtransects.csv")
fish <- read.csv("RawFiles/FishID.csv")

```

```{r configuredata}

#############################
# Melt DataFrame
#############################

dat <-melt(VS.Master, measure.vars = c('T1.10_15', 'T1.15_20', 'T1.20_25', 'T1.25_30', 'T1.30', 'T1_Unknown','T2.0_5', 'T2.5_10', 'T2.10_15', 'T2.15_20', 'T2.20_25', 'T2.25_30', 'T2.30', 'T2.Unknown'))

#Rename the new variables
names(dat)[names(dat) == 'value'] <- 'frequency'
names(dat)[names(dat) == 'variable'] <- 'sizeclass'

dat <- dat[,-c(2,3,5,8:14)] #Get rid of unwanted columns
head(dat)

#Make new variable for each pass of the transect. "first" = first pass; "second" = second pass

out <- substr(dat$sizeclass, 0, 2)
dat$pass <- ifelse(out=="T1", "first", "second")

dat$treatment <- as.factor(ifelse(dat$NoTake == "TRUE", "protected", "fished"))
dat$pnum.f <- as.factor(dat$UniquePatch.Num)
dat$transect.f <- as.factor(dat$Transect)

dat$location <- ifelse(dat$sub == "Seagrass", "Belize", "Florida")
dat <- dat[dat$UniquePatch.Num != 13, ]

# Get transect numbers
numtransects <- read.csv("RawFiles/numtransects.csv")

```

```{r subsettopatches}

df <- dat[dat$UniquePatch.Num < 20, ] # subset to patches

df <- df[df$pass == "second", ] # subset only to the second pass

```

```{r summary}
#####################################################
# Whose Who? 
#####################################################
#What species did I see? Who was most common? Broken down by country. 

#All Species

all.numbers <- aggregate(df$frequency, list(Common.Ident = df$Common.Ident,sub = df$sub), sum, na.rm=TRUE)
names(all.numbers)[names(all.numbers) == 'x'] <- 'frequency'
mostcommon.belize <- all.numbers[all.numbers$sub == "Seagrass",]
Ord.x <- order(mostcommon.belize$frequency, decreasing = TRUE)
mostcommon.belize <- mostcommon.belize[Ord.x, ][1:20, ] 

mostcommon.fk <- all.numbers[all.numbers$sub == "Macroalgea",]
Ord.x <- order(mostcommon.fk$frequency, decreasing = TRUE)
mostcommon.fk <- mostcommon.fk[Ord.x, ][1:20, ]


#Piscivores/Herbivores
  #I want to create a table of the most commonly encountered piscivores. It doesn't matter what pass they were seen on... it doesn't matter if they were in NoTake or Fished areas. It does matter the country. 

pisc.herb.numbers <- aggregate(df$frequency, by = list(Common.Ident = df$Common.Ident, pisc.herb = df$Piscivore_Herbivore, sub =df$sub), FUN = sum)
names(pisc.herb.numbers)[names(pisc.herb.numbers) == 'x'] <- 'frequency'

#Herbs in Belize
herb.belize <- pisc.herb.numbers[pisc.herb.numbers$sub == "Seagrass" & pisc.herb.numbers$pisc.herb == "Herb",]
Ord.x <- order(herb.belize$frequency, decreasing = TRUE)
herb.belize <- herb.belize[Ord.x, ][1:10, ] 

#Herbs in Florida
herb.fk <- pisc.herb.numbers[pisc.herb.numbers$sub == "Macroalgea" & pisc.herb.numbers$pisc.herb == "Herb",]
Ord.x <- order(herb.fk$frequency, decreasing = TRUE)
herb.fk <- herb.fk[Ord.x, ][1:20, ] 

#Pisc in Belize
pisc.belize <- pisc.herb.numbers[pisc.herb.numbers$sub == "Seagrass" & pisc.herb.numbers$pisc.herb == "Pisc",]
Ord.x <- order(pisc.belize$frequency, decreasing = TRUE)
pisc.belize <- pisc.belize[Ord.x, ][1:10, ] 

#Pisc in Florida
pisc.fk <- pisc.herb.numbers[pisc.herb.numbers$sub == "Macroalgea" & pisc.herb.numbers$pisc.herb == "Pisc",]
Ord.x <- order(pisc.fk$frequency, decreasing = TRUE)
pisc.fk <- pisc.fk[Ord.x, ][1:10, ] 

```

```{r makenewdataframeformodeling}

# Make a new data frame to use as the basis of the grazing modfls 

#for second pass
aw.second <- ddply(df[df$Piscivore_Herbivore == "Herb", ], .variables = c("pnum.f", "treatment", "location", "sub"), summarise, herbn = sum(frequency))
aw.second$predn <- ddply(df[df$Piscivore_Herbivore == "Pisc", ], .variables = c("pnum.f", "treatment", "location", "sub"), summarise, predn = sum(frequency))[,5]
aw.second$invert <- ddply(df[df$Piscivore_Herbivore == "Invert", ], .variables = c("pnum.f", "treatment", "location", "sub"), summarise, invert = sum(frequency))[,5]
aw.second$other <- ddply(df[df$Piscivore_Herbivore == "other", ], .variables = c("pnum.f", "treatment", "location", "sub"), summarise, other = sum(frequency))[,5]
aw.second$parrot <- ddply(df[df$parrot_pred == 1, ], .variables = c("pnum.f", "treatment", "location", "sub"), summarise, parrot = sum(frequency))[,5]

#aw <- cbind(aw, all.size[,-1])
#aw.second <- cbind(aw.second, all.size2[,-1])

#aw <- merge(aw, numtransects, by.x = "pnum.f", by.y = "UniquePatch.Num")
aw.second <- merge(aw.second, numtransects, by.x = "pnum.f", by.y = "UniquePatch.Num")

#aw.norm <- aw
#aw.norm[,5:9] <- aw[,5:9]/aw$Num.Transects

aw.second.norm <- aw.second
aw.second.norm[,5:9] <- aw.second[,5:9]/aw.second$Num.Transects


#write.table(aw.norm, "RawFiles/vsall.csv", sep = ",", row.names = F)
#write.table(aw.second.norm, "RawFiles/vssecond.csv", sep = ",", row.names = F)

```

```{r densitycalculations}

den <- ddply(df[df$Piscivore_Herbivore == "Herb", ], .variables = c("pnum.f", "treatment", "location", "sub", "Transect"), summarise, herbn = sum(frequency))

den$pisc <- ddply(df[df$Piscivore_Herbivore == "Pisc", ], .variables = c("pnum.f", "treatment", "location", "sub", "Transect"), summarise, pisc = sum(frequency))[6]

den$invert <- ddply(df[df$Piscivore_Herbivore == "Invert", ], .variables = c("pnum.f", "treatment", "location", "sub", "Transect"), summarise, invert = sum(frequency))[6]

den$other <- ddply(df[df$Piscivore_Herbivore == "other", ], .variables = c("pnum.f", "treatment", "location", "sub", "Transect"), summarise, other = sum(frequency))[6]

den$parrot <- ddply(df[df$parrot_pred == 1, ], .variables = c("pnum.f", "treatment", "location", "sub", "Transect"), summarise, parrot = sum(frequency))[6]

area <- 50*10

apply <- c("herbn", "pisc", "invert", "other", "parrot")

for(i in 1:length(apply)){
  den[,c(10+i)] <- den[, c(apply[i])] / area
}

names(den) <- c(names(den[,1:10]), "herb.den", "pisc.den", "invert.den", "other.den", "parrot.den")

apply2 <- c("herb.den", "pisc.den", "invert.den", "other.den", "parrot.den")

den2 <- aggregate(den[, c(apply2[1])], by = list(pnum.f = den$pnum.f, treatment = den$treatment, location = den$location, sub = den$sub), FUN = mean)
names(den2) <- c("pnum.f", "treatment", "location", "sum", "herb.den")

for(i in 2:length(apply2)){
den2[, c(apply2[i])] <- aggregate(den[, c(apply2[i])], by = list(pnum.f = den$pnum.f, treatment = den$treatment, location = den$location, sub = den$sub), FUN = mean)[5]
}

formerge <- den2[, c(1, 5:9)]

second.pass <- merge(aw.second.norm, formerge, by = "pnum.f")

#write.table(second.pass, "vssecond.csv", quote = F, sep = ",", row.names = F)

```








